### ISSUE TITLE
Training categorizer

### ISSUE THREAD

**Issue by nirvikara** [umyelab/LabGym#1]
Hi, 
Your work looks really interesting and I plan to try out LabGym.  I plan to generate some videos for training and have a few questions about the requirements-
1.  Are there any restrictions on the fps of the videos used for training?
2.  Should the fps of the videos used to infer behavior be the same as those used for training, or does LabGym automatically read the video metadata and adapt accordingly? In other words, can I train the categorizer using 1fps videos and infer a 60 fps video?
3.  Some of the behaviors I am interested have a bout length of 3 seconds while other behaviors like sleeping can be in the order of minutes. When I am preparing the training videos, should all videos be of the same duration as the shortest behavior I have? i.e. if I am preparing a video for 'sleeping' for instance should I have multiple 'sleeping' videos of 3 seconds each or can I have videos of varying durations for different behaviors?
4. If I prefer not to have background subtraction for some behaviors but I want it ON for other behaviors, is there a way to implement this?

**Comment by yujiahu415** [comment]
Hi nirvikara,

Thank you for your interest! As for your questions:

1. There is no restriction on the fps of your videos as long as you keep the fps of your training videos the same as that of the videos for analysis.

2. The fps of the videos used to infer behavior should be the same as those used for training. The duration of a short animation used for training / categorizing in LabGym is measured in number of frames. For example, if you use 30 frames at 30 fps as the duration of a behavior (1 sec) for training, LabGym will always take 30 frames when inferring the behavior, which means, LabGym will assess only 0.5 sec if the fps of the video used to infer the behavior is 60. This might still work, but the accuracy could be compromised.

3. First of all, you don't need to prepare the short animations (videos) for training by yourself. You can use the GUI to input some parameters like the duration of a training animation and LabGym will output the cropped, unsorted animations from the original videos and you only need to sort the animations (and their paired motion images) by putting them into different folders under the names of different behaviors. You need to keep the duration of all the training animations the same for training one Categorizer. This is because the inputs of Categorizer need to be consistent all the time during inferring. I can use padding to make inputs of different duration the same length but it's artificial. So I thought letting the Categorizer to ignore irrelevant frames might be a better choice. That means, for example, during a 30-frame animation 20 frames are behavior-relevant while 10 are irrelevant, and if you have 200 such animations for training, the behavior-relevant frames in different animations would have similar spatiotemporal information while irrelevant frames would seem to be random. During training, the consistent behavior-relevant information would stand out and be learned and the random irrelevant info would fade. So you may choose the duration of the longest behavior if the durations of the different behaviors are different. But please note that longer duration means longer processing time (higher computation cost). So you may want to keep the duration as short as possible. If the duration of a behavior is long but the behavior is periodic / repetitive, you may consider to take just one cycle of the behavior. For example, I imagine that sleeping is repetitive immobile, with some characteristic poses / breathing rhythm?, and you may just take the shortest cycle. Maybe 5-second observation time is already enough for you to determine whether the animal is / or is likely sleeping?

4. In current version of LabGym you need to have (or not have) the background subtraction for all the behaviors that can be distinguished by one Categorizer. But what you mentioned is a good point. I will consider to implement this in the future versions of LabGym.

Let me know whether these answers have addressed your questions.

**Comment by nirvikara** [comment]
Got it. Thanks for the clarification :)  I will open new issues with specific questions.
