### ISSUE TITLE
No GUI mode documentation

### ISSUE THREAD

**Issue by vincent-legoll** [umyelab/LabGym#146]
Hello,

what do you think about a no GUI version ?

To enable users to launch processes via command line.

**Comment by yujiahu415** [comment]
Hi,

LabGym can run from command line and without GUI. For now, you need to take a look at its source code and understand what each function does. But a detailed instruction and user guide on how to import and use each function from command line will be included later this year.

**Comment by vincent-legoll** [comment]
OK, very good, I updated the issue title to reflect that.
Thanks a lot.

**Comment by yujiahu415** [comment]
Thanks!

**Comment by yujiahu415** [comment]
Hi @vincent-legoll ,
Just so you know, I have added the documentation in the [extended user guide](https://github.com/umyelab/LabGym/blob/master/LabGym_extended_user_guide.pdf) on how to use the functions in LabGym that heavily reply on GPU via command prompt, so that users can benefit from using clusters / servers that have powerful GPU yet don't have virtual desktops. For other functions, a local machine is sufficient.
