### ISSUE TITLE
Unable to getting started with LabGym

### ISSUE THREAD

**Issue by SlowSD** [umyelab/LabGym#16]
Hey,

I was trying to use LabGym for my project.

I have installed latest version of python viz, python-3.11.2-amd64
I have installed LabGym using command: pip install LabGym
One error I am encountering is: python setup.py egg_info did not run successfully.

After this, I have successfully ran command: python3

However, upon using the main command viz, from LabGym import gui
This is an error that I am seeing.

>>> from LabGym import gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'LabGym'

Kindly help in fixing this issue.

Thank You in advance.

**Comment by yujiahu415** [comment]
Hi,

You may try an older version of python3 since the setuptools or wheel might not be updated to be compatible with the latest python3. Try uninstalling the current python3.11.2 and then install a python3.9.X or a python3.10.X version and let me know if you still have the problem.

**Comment by matwku** [comment]
Hi, 

Thanks for developing the software, looks very exciting!
I would like to give it a try on our data, but after what seemed a successful installation, I encountered problems to prompt GUI...

Here're error details:
(LabGym) MacBook-Pro-2:~ Mateusz$ python3
Python 3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from LabGym import gui
Illegal instruction: 4

I'm wondering if processor architecture may have something to do with it? I'm using Macbook M1 Pro (2021) with Ventura 13.4.

I would greatly appreciate your help!

Thanks, 
Mat :)

**Comment by yujiahu415** [comment]
Hi Mat,

Thank you for using LabGym! I did some search and the 'Illegal instruction: 4' is likely because the installed tensorflow does not work for M1. You may try uninstall the current tensorflow by 'python3 -m pip uninstall tensorflow' and install a Mac version following the steps on this: https://developer.apple.com/metal/tensorflow-plugin/. Hopefully this can solve the issue but let me know if it doesn't.

By the way, the new LabGym 1.9 requires an independent installation of Detectron2 (it was not listed on pypi so can't be installed together with other dependencies). So after you installed LabGym, make sure to install Detectron2 by python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'. Or refer to this page for installing Detectron2: https://detectron2.readthedocs.io/en/latest/tutorials/install.html.
