### ISSUE TITLE
Unable to download a package

### ISSUE THREAD

**Issue by odong8322OU** [umyelab/LabGym#162]
I am having issues with training the detectors. I have already annotated images with Roboflow, so I have the folder with the annotations json and the 'train' folder. However, when I try to train the detectors, it gives me this error: 
<img width="1466" alt="Screenshot 2024-06-27 at 2 49 19 PM" src="https://github.com/umyelab/LabGym/assets/174055084/595b113d-0b70-49e5-81c4-61e4d27b6d9a">
I put my error into ChatGPT and it tells me that something might be wrong with my Pytorch- something about incompatible versions. However, I reviewed the instructions on Github and confirmed I had the right version installed. 

I have also tried this on different networks, with the same result. Is there a fix for this? 
Thanks!

**Comment by yujiahu415** [comment]
Hi,
First of all, which PyTorch version did you use? Second, did you try this on a different computer? This error might be caused by the network configuration on this computer prevent you downloading the maskRCNN hosted in the detetron2 server. So would it possible for you to try a different computer to see if you still get this error?
Alternatively, you can send me / share with me the roboflow dataset via email (henryhu@umich.edu) and I can train a Detector for you and send the trained Detector to you.

**Comment by odong8322OU** [comment]
The PyTorch version I use is 2.0.1, which seems to be the correct version I should have. I will attempt to install it on another computer and let you know if any other issues arise.

**Comment by yujiahu415** [comment]
Sure! Let me know if you have any other issues.
