### ISSUE TITLE
Can't find my pattern images

### ISSUE THREAD

**Issue by gold90123** [umyelab/LabGym#17]
![image](https://user-images.githubusercontent.com/76434705/229292577-15fb7f76-7aa9-4d84-8624-dd2184fea994.png)
There's no pattern images in my folder, only the animation.
It should produce both animation and image after the Generate Behavior Examples step, am I right ??
But it seems nothing wrong from the cammand.
![image](https://user-images.githubusercontent.com/76434705/229292748-0a4ec08d-5f7d-4f03-b2b4-26316e6904fb.png)

**Comment by gold90123** [comment]
alright, I tried a rat video, and it produce the animation also pattern image.
Maybe Pig video is not suite for this model ?

**Comment by gold90123** [comment]
I figured out why I didn't have the pattern image before !!
It was because I had chose 'Yes' of the 'Including body parts' option, and set the STD value to 100.
Therefore, I assume that my STD value was too high, resulting in 0 pattern images being produced.
However, when I set the STD value to 0, everything returned to normal.

**Comment by yujiahu415** [comment]
Great to hear that! Just one comment: base on what presented in the animations, it seemed LabGym did not detect the animal correctly, either because the background was not static or the time window for background extraction was not appropriately selected. Anyway, we are developing a new detection module for LabGym 2.0 and the background will no longer be an issue after the new detection module is implemented.

**Comment by gold90123** [comment]
@yujiahu415 Thanks for the comment, i'm very excited about the Mask-RCNN in LabGym 2.0.
I sincerely appreciate your effort.
