### ISSUE TITLE
Issues with generating behavior examples using a detector

### ISSUE THREAD

**Issue by s-papolu** [umyelab/LabGym#212]
Hello,

Firstly, thank you for developing LabGym! I'm having issues generating behavior examples using a detector with v2.5.0. I'm using the interactive_advanced setting with a framesize of 736. Although testing the detector gives me good results, once I generate behavior examples the mouse is not picked up on.

For instance, this is how the images are being annotated via VGG annotator, where I have 2 ROIs and one mouse. 
![Trial     1_processed_6950](https://github.com/user-attachments/assets/6bbf34a6-5a68-4ef7-ac33-e99c3a79ed84)

The detector itself has a mAP of about 76% and is decent at picking up just the mouse's head and the 2 ROIs. However, generating behavior examples gives me images like this.
![Trial     1_processed__0_25_len25_scdt0_itadv](https://github.com/user-attachments/assets/a52faecb-0786-4448-852e-6215f0f4ca1e)

It seems like the program isn't able to identify the mouse even though the detector itself was able to. When I generate examples, I include all annotated areas in the checklist, as well as make sure that the framesize is at 736. Are there any settings I should change when generating behavior examples?

**Comment by yujiahu415** [comment]
Hi,

What were the 'animations' in behavior examples you generated like? The mouse head was not showing in the animations either? It's possible that when mouse enters into a ROI it will not be shown in the pattern image because it only shows the outlines of detected object and the mouse was inside an outline.

I would suggest you to use the new function I recently added into LabGym, which is called 'Draw Markers' in 'Preprocessing Module' for this type of analysis. You can upgrade LabGym to its latest v2.5.2 to use that function.

If my understanding is correct, you want to analyze how the mouse interact (like goes into or out of) a specific region, right? The 'Draw Markers' function allows you to use different colors to mark specific regions, and then let LabGym Categorizer distinguish the region(ROI)-referenced behaviors of the mouse. In this case, you probably even don't need to use the Detectors if the illumination in your videos is stable. By the way, although VGG annotator can work for LabGym, we recommend to use Roboflow because it's way less laborious for annotation in Roboflow--it has automatic detection algorithm to detect the outlines of objects so you don't need to hand draw the outlines by your self.

Would it be possible to let me know what kind of analysis you want to do (like what behavior you want to analyze)? And also, would it be possible to send me an example video so I can show you how to use the 'Draw Markers' function for your analysis?

**Comment by s-papolu** [comment]
Hello,

Sorry for the late response! In the animations, sometimes the entire area would be included, but sometimes it would zoom in on just one of the ROIs instead of where the mouse is. Even when the entire area is included, the pattern image does not include the mouse head.

As for the specific behavior, I am trying to analyze how much time the mouse interacts with either the left ROI or the right ROI in order to understand its social interactions with other mice or objects, although this trial I am analyzing is just a control trial.

Thank you for the other information about 'draw markers'! I did try to use it earlier but it lowered the detector mAP significantly. Is it possible to use 'draw markers' without needing to train and test a detector? In that case, how will the program be able to pick up on the mouse head itself? Furthermore, is there an email that I can send the example video to so you can view it? Thank you!

**Comment by yujiahu415** [comment]
Hi,

Thanks for the information! You can send me an example video at yujiahu415@gmail.com. After I see the video, I can have more specific suggestions.

As general suggestions, the 'draw markers' function can be used creatively to make the analysis very efficient. And it can be used without the need of a Detector--as long as the background and illumination is stable enough (you can then use 'subtract background' as the detection method, which is much faster than the Detector).

As for detecting the head, why do you need to specifically detect the head? If you just want to analyze how much time the mouse interacts with the two ROIs, my rough guess is that tracking the whole body would also work well for this purpose--and it's much easier than just tracking the head. This is because there's no visualizable edge between the head and the rest of the body for the Detector to distinguish. But if you have to detect just the head, then you have to use the Detector. But I think there's still a way to use 'draw markers' function without compromising the detection accuracy by the Detector.

**Comment by s-papolu** [comment]
Hello,

Great, I just sent you an email!

As for detecting just the head, I initially was annotating the full body. However, I was concerned that any instance where the mouse's body (such as just the rear end of the mouse) was in an ROI would be counted as an interaction, even though it wouldn't technically be interacting with that ROI. I actually haven't tried the combination of 'draw markers' with subtract background, and have only used 'draw markers' with a detector.

Thank you!

**Comment by yujiahu415** [comment]
Hi,

First, thank you for allowing me post the answer here including the data. This would be helpful if other users have the same question. The data is from Fioravante Lab at UC Davis.

For this video I used the first 5 minutes to generate behavior examples and sorted them to train a Categorizer, and then used the remaining 5 minutes for testing. So the testing period is not used in training, which can give you an idea of how generalizable the Categorizer to unseen videos.

The conclusion is LabGym can work very well on this type of experiment. 

1. you can preprocess your videos by cropping frame and enhancing the contrast by 2.0. See the example video frame before and after:

<img width="711" alt="before" src="https://github.com/user-attachments/assets/669870de-655b-4f82-a9cb-339f3ce5c7e6">

<img width="444" alt="after" src="https://github.com/user-attachments/assets/32ee4838-33a6-40d8-b795-432e9963cd59">

&nbsp;

2. Then draw markers. Instead of drawing a single big circle, draw multiple small circles inside the border of the ROIs so that the border can be marked clearly and with directional information. See example video frame after marker drawing:

<img width="444" alt="marked" src="https://github.com/user-attachments/assets/d7025fb9-d56e-4432-a259-9b96bdc553d2">

&nbsp;

3. Next, generate and sort behavior examples. Since the background and the illumination in your video is quite stable, you don’t need to use Detectors. Instead, use background-subtraction-based method and select the first 20 second as the time window for background extraction. This method does not require GPU and is super fast (~20 second processing time for 1,000 frames during analysis on my computer). When generating behavior examples, choose ’non-interactive mode’, including background in Animations, do not include body parts in Pattern Images, the duration of one behavior example is set to 12 frames (~0.5 second because the fps is 25). I used 3 categories of behaviors, ‘interact blue’, ‘interact red’, and ‘background’. The behavior examples are like:

Interact blue: when the mouse head is inside blue-marked ROI and facing the cup

<img width="701" alt="interact blue" src="https://github.com/user-attachments/assets/f593cba5-0f46-45ac-b27c-957381f5caa3">

&nbsp;

Interact red: when the mouse head is inside red-marked ROI and facing the cup

<img width="688" alt="interact red" src="https://github.com/user-attachments/assets/99c423da-ffc6-44b0-8db0-7d4a58aedff6">

&nbsp;

Background: outside both ROIs, or passing by / staying in an ROI but without facing the cup

<img width="692" alt="background" src="https://github.com/user-attachments/assets/5d212a5b-41a2-4371-b667-bf65170f48e7">

&nbsp;

The sorting is pretty simple. It took me ~10 minutes to finish. I selected and sorted ~1000 pairs of background, ~100 pairs of interact blue, ~150 pairs of interact red. You can include more videos to add more examples and can also refine the dataset, for example, delete those repetitive ones. You don’t need too many examples, 300 pairs well-selected examples per category is good enough to train an accurate Categorizer.

&nbsp;

4. Training Categorizer. Since the behavior can be distinguished more easily by watching the Animations (which include the background information) than by watching the Pattern Images in this case, you can put more weight on the Animation Analyzer when customizing the Categorizer. Since the frame / image size of the generated behavior examples ranges from 33 X 33 to 85 X 86, you don’t need to go too high for the input size. So you can customize a Categorizer of Animation Analyzer (level 3, input size 32) and Pattern Recognizer (level 2, input size 16). You can also try Categorizers with different settings to see which one works best. Some other settings you could try: Animation Analyzer (level 3, input size 32) and Pattern Recognizer (level 1, input size 8); Animation Analyzer (level 4, input size 32) and Pattern Recognizer (level 2, input size 16). The augmentation methods: all except ’shearing’ and ‘rescaling’. Also augment the validation data. The training is pretty fast, which took less than 30 minutes on my computer.

&nbsp;

5. Testing. You can test the trained Categorizer on other videos to see how it generalizes. To import a trained Categorizer, use ‘pipshow LabGym' to find where LabGym folder is in your computer, and then put the trained Categorizer folder under '…/LabGym/models/‘, and then you can access the Categorizer through LabGym GUI.

Remember to draw the markers the same way for all your videos.

The Categorizer works well in testing, although there’s still room to improve. Some screenshots from the annotated video:

Interact with blue-marked ROI:

<img width="1220" alt="interact blue 1" src="https://github.com/user-attachments/assets/76d4605f-98d6-4d2f-8aa8-e3c93b7cad24">

&nbsp;

Interact with red-marked ROI:

<img width="1196" alt="interact red 1" src="https://github.com/user-attachments/assets/6303bed4-dd4b-4136-81a0-86b907694a71">

&nbsp;

Background—the head is facing outside while the rear end of the body is inside an ROI:

<img width="1217" alt="background 1" src="https://github.com/user-attachments/assets/427b58ed-2a8e-40ea-a6aa-230027d85203">

&nbsp;

Background—passing by an ROI:

<img width="1053" alt="background 2" src="https://github.com/user-attachments/assets/c4aeef8b-8b6d-4700-bd34-9143bd20454e">

&nbsp;

Sometimes when the head is facing outside and the rear end of the body is inside an ROI it was categorized incorrectly. But this can be improved by adding more examples of this scenario into ‘background' category, or increase the recording resolution to make the two ears more visible in the video because the two ears are in different color than the body and can be used by the Categorizer to distinguish head from rear end of the body. You can also make the 3 behaviors into finer categories if you want.
