### ISSUE TITLE
video annotations loading in mirror image

### ISSUE THREAD

**Issue by meghanflanigan** [umyelab/LabGym#215]
Hi, 

We are having a new issue where when we analyze videos and generate and annotated video, all of the text displayed shows up as a mirror image. All of the settings are the same as when it was working properly, and the videos we are annotating come from the same cohort of videos (but not the same exact videos) we used to train the categorizers. Any idea what might  be going on here? 

Thanks!

**Comment by yujiahu415** [comment]
Hi,

What does the 'mirror image' look like? Can you please show me an annotated video or a screenshot to help me understand this?

And also, does LabGym output any errors? If so, can you also screenshot the error message? And which version of LabGym did you use?

Thanks!

**Comment by meghanflanigan** [comment]
Here is a screen shot of the backwards text 
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/b8b446f5-0a29-4e45-8345-216a3061f10d">

We did not see any errors output when the annotated video was being made. We are using labgym version 2.5.2

**Comment by yujiahu415** [comment]
Okay this is a bit weird. The frame is just upside down. It might be related to which camera you used to record the video and which media player you used to play the video. Are these the same as before? If so, can you try to use preprocessing module in LabGym to preprocess one of your testing videos that had this issue, from example, trim the first 2 minutes to do a quick test? I was wondering if the preprocessing step can revert the frames to make them look right. Can you also send me a video with this problem so I can take a closer look to see what the problem is? Thanks!
