### ISSUE TITLE
Clarification on Categorizer Accuracy

### ISSUE THREAD

**Issue by s-papolu** [umyelab/LabGym#227]
Hello,

I hope this finds you well! I have been training and testing categorizers after using the "draw marker" function on videos. However, I seem to be having issues with achieving a similar accuracy percentage after training and after testing.

For instance, I sorted about 2500 behavior pairs into 3 behavior categories, and got accuracies of 90% for all, after training a categorizer. Below are the metrics after training.
![Screenshot 2024-11-06 100544](https://github.com/user-attachments/assets/8e21f66e-793a-4ba2-971a-ab2b22dfa602)
However, using this categorizer to analyze videos had results as shown below.
![Screenshot 2024-11-06 101242](https://github.com/user-attachments/assets/1fb82bf7-037d-479a-82ed-c0780416a7f9)
![Screenshot 2024-11-06 101458](https://github.com/user-attachments/assets/9837f014-ef95-4d7c-bb96-38892da0e72c)

I trained another categorizer using about 5000 behavior pairs, sorted into 3 behavior categories, and got accuracies of 92%. However, I found the same issues after testing the categorizer and using it to analyze videos.

I am not sure when a categorizer is considered "good enough," or when to stop attempting to increase the accuracy, especially if the analysis module finds that the categorizer is unable to accurately sort behaviors, despite having a training accuracy of >90%. Do these results just mean I need to increase the variety of behavior examples I am sorting, or are there too many examples in the first place (with about 5000 pairs)?

I also wanted to ask if raising or lowering the uncertainty level would impact the analysis results? I have tried 10% as well as 50%, though there has not been much of a difference in that mistakes such as the ones above are still being made.

Please let me know if you need any more information, and thank you for your help!

**Comment by s-papolu** [comment]
Hello,

1. If I had to estimate it, I would say the mistakes occurred maybe for a total of 2 or 3 minutes out of a 10 minute video, though much of that video was the mouse walking around without interacting. The mistakes mostly happened when the mouse was interacting with either side. 
2. I apologize, I worded this incorrectly! I meant there were about 2500 examples in total, so about 1250 pairs. For the categorizer trained using about 1250 pairs, for which I sent the training metrics, interacting blue had 94 pairs and interacting orange had 133 pairs. For the categorizer using about 5000 examples, or about 2500 pairs, interacting blue had 159 pairs and interacting orange had 249 pairs.
3. The categorizer was set to a complexity level of 4 (animation analyzer) and 2 (pattern recognizer). The input shapes were 32 (animation analyzer) and 16 (pattern recognizer). I augmented both training and validation examples with everything but random shearing and rescaling.
4. I can share the dataset via email, if that's okay!

Thank you again!

**Comment by yujiahu415** [comment]
No worries!

Based on your estimate, the accuracy is around 70% for the interactive behaviors, which is consistent with the training metrics (in which the f1-scores are 72%).

I also checked your sorting, and it is generally good. I did some refinement on the sorted behavior examples (5000). There's one pair of examples in interacting orange that should belong to the background, and I moved them to the background category. I also removed some redundant ones in the background category. I used the refined example dataset to train a Categorizer at the setting:
Behavior mode: Non-interactive
Animation Analyzer complexity level 3, input size 64
Pattern Recognizer complexity level 1, input size 8
Gray scale Animation Analyzer: No
Length: 12 frames
Background free Animation Analyzer: No
Include body parts in Pattern Recognizer: No
Augmentation methods: All except rescaling and shearing
Augment validation data: Yes

The setting I chose was simpler than your previous setting but achieved similar overall accuracy as your setting (93%). Specifically, I set the Pattern Recognizer to the lowest complexity but increased the input size of Animation Analyzer to 64, because the behaviors can only be distinguished by watching the animations rather than the pattern images. So, I put more weight on the Animation Analyzer and minimum weight on the Pattern Recognizer. Please also note that the "Gray scale Animation Analyzer" must be set to "No" because you use different colors to distinguish different behavior. You also need to make sure that "Background free Animation Analyzer" is set to "No" because you include background in animations. These two options won't affect the accuracy of training but will significantly affect that of analysis.

Some other suggestions:
1. The number of examples in the background category is greater than 2000 pairs, but you don't need that many examples in one category. You can consider selecting the most representative ones to make the number around 1000 pairs.
2. The number of examples in the other two categories is relatively low (~100~200 pairs). You can sort more examples to make them ~300 pairs for each.
3. I saw all the examples came from just one video. You probably want to use multiple videos to generate examples and sort, so that the examples can be more representative and cover more diverse scenarios in different videos or animal individuals.

I sent you the refined example dataset and the Categorizer I trained for you. You can test this Categorizer on the video that had that issue and let me know if there's any improvement.
