### ISSUE TITLE
Error in the training of a detector

### ISSUE THREAD

**Issue by apenemo** [umyelab/LabGym#34]
Hi 

After having succesfully trained a detector on a small sample of annotated images from roboflow. I tried to train a new detector on a bigger dataset and I faced mutltiple times this error: 

![image](https://github.com/umyelab/LabGym/assets/110259129/8f7af032-9cde-4977-85ce-02e3ed8c0b45)

I annoted the data using the same method as before, I exported under the coco format. 
I used an infering framesize of 256 and 200 iterations. 

What I do not understand is that the detector seems to have been successfuly trained when using an infering framesize of 32 and a 100 iterations. 

I wonder if the problem comes from my dataset or from my misunderstanding of the LabGym's training process. 

Thank you

**Comment by yujiahu415** [comment]
Hi,

The error message indicates that there is no 'segmentation' category in your annotation file. You can use notepad to open your 'xxx.json' annotation file to see if there is a 'segmentation' category in it, like this:
<img width="663" alt="Screen Shot 2023-06-22 at 2 17 10 PM" src="https://github.com/umyelab/LabGym/assets/71684256/fb021ab2-1d5b-45b1-889b-4404e2d25b5c">

If not, please make sure when you annotate images, choose 'Instance Segmentation' for the annotation type, and select 'COCO instance segmentation' format when export the '.json' file. But if 'segmentation' is in your annotation file, then this might be caused by a bug in LabGym v1.9.4.

I'm working on a new version v1.9.5 and will release it by tomorrow. This version includes major improvement in GUI, bug fix, and also includes the basic analysis of interactive (social) behavior. Please check back tomorrow!

**Comment by yujiahu415** [comment]
New version is out. Let me know if you still have the issue after confirming the annotation file is correct.

**Comment by apenemo** [comment]
Hi thanks for your quick response. I download the latest vesion ( the interface is much better by the way ! ) and it still does not work. My json file does contains segmentation. I exported my dataset from robolfow using the "coco" format, ( and note " coco instance segmentation" which was not proposed to me).

Is it possible that, only one annodated picture in my dataset is not annotated in the segmentation format and that It causes the whole trained process to fail ? 


My training dataset only comes from roboflow and has only been exported in the json format, here is a screenshot of a part of it
![image](https://github.com/umyelab/LabGym/assets/110259129/d505f3b3-e635-4bd9-b56b-d3800c2caffb)

once again, thank you for your priceless support.

**Comment by apenemo** [comment]
It appears indeed that one of my annotated picture had an abnormal annotation. I finally found. One extremely small sized zone was present on an already marked individual. 

I wonder if the error came from the unexpected overlap between the two annotations or from the extremely small size of the unattended annotation ( with a maximum zoom on roboflow i was only able to so a few pixels of the annotation box). 

It seems that I am on good tracks to finally train my detector !
