### ISSUE TITLE
[error] requested array has an inhomogeneous shape

### ISSUE THREAD

**Issue by apenemo** [umyelab/LabGym#45]
Hello, while training my categorizer on a bigger data set an error occured. 

here it is. 

![image](https://github.com/umyelab/LabGym/assets/110259129/3ae970aa-cd09-457c-8fa5-3f10176009ea)

My last successfull attempt a training a categorizer was on a smaller dataset, with both complexity level at 1.

Now I have a bigger dataset and I want to train the categoriser with both complexity level at 7 since the behaviours I study are indeed very complex, but I face this new error.

Thanks for the help

**Comment by yujiahu415** [comment]
Hi,

The error message indicated that the animations in your behavior examples were of inconsistent duration. Please make sure every animation in your behavior examples is of the same duration (number of frames).

For example,  if you generated some behaviors example with 15 frames as the duration of animations, and later generated some with 14 frames, and then combined these two sets of examples to train a Categorizer and specified 15 frames as the input duration of the Categorizer, this error would occur.

**Comment by yujiahu415** [comment]
Hi,

I just released a new version, which makes the training work for animations with inconsistent duration. But be aware that the inconsistent duration can make the training less efficient. So you'd better still make all the training examples the same duration. Besides, since you're going to train a Categorizer with complexity level of 7, you may need more training examples. From what you showed here, it seemed you only had 133 examples in total, which is far from the number required for a good training. Did you choose any data augmentations? If not, I suggest you to choose to augment data to increase the example amount if you have only a few examples and don't want to include more.

The new version should also fix the issue you had for sorting the behavior examples. You can upgrade LabGym to the latest version.

**Comment by apenemo** [comment]
Hi sorry for not answering sooner.

You were right, I had 60frames and 45 frames animations in the same dataset which caused the error. 

to answer your second comment, no there was no data augmentation, i chose not to use them to check if it was the cause of the error I faced. You are absolutely right about the amount of data I should use. I had only 133 examples because I chose not to work on my whole dataset for the first tries. 

After you pointed me what the problem was, I started generating behaviours example ( 45 frames animation taken every 50 frames) for my entire dataset (85 videos of approximately 25seconds). Even with my 60vCPU, the process is quite long as it seems that only 30 vCPU seems to "work" on this task. It should be over by monday. Only then will I be able to upgrade LabGym.

After having sorted every behaviour in according folders, I will try again to train the categorizer, probably with data augmentation too. 

Thanks !

**Comment by yujiahu415** [comment]
Categorizer with higher complexity usually requires more training examples for good generalizability. And more training examples would always benefit the training. So I would suggest you always add data augmentations.

**Comment by yujiahu415** [comment]
LabGym2 is out. It can analyze complex interactive behaviors now and should fix the sorting issues you encountered previously.

**Comment by apenemo** [comment]
Thank you very much, I will try to train a categorizer on grooming behaviours using LabGym 2.0. I will keep you updated.
