### ISSUE TITLE
Generate Behavior Examples w/ Detechron2 Question

### ISSUE THREAD

**Issue by a8cone** [umyelab/LabGym#46]
Hi LabGym users,

I want to analyze some forced swim test videos and use Detechron2 to find the object (animal) instead of background subtraction. 

I have already annotated a small subset of the animals and used the exported json file with the training images loaded into LabGym. I get the error below when I try to Generate Behavior Examples. 

Any help to help me understand what this error means would be helpful.

![image](https://github.com/umyelab/LabGym/assets/60786631/a5e64a75-8c8d-40e0-ae67-d43a0d2f8ef1)

(Hopefully this helps others as well if this occurs.)

Thanks in advance!

Aaron

**Comment by yujiahu415** [comment]
Hi Aaron,

The error message indicates the mouse was not properly detected. You may first do a quick test to see if the mouse can be properly detected by the trained Detector: 

Go to 'Analyze Behaviors', select 'No behavior classification, just track animals and quantify motion kinematics' in the 'Select a Categorizer..' and use the Detector to do a quick analyze. It will output an annotated video with the animal outline annotated in the video so that you can see if the mouse can be detected.

Let me know how it goes.

**Comment by yujiahu415** [comment]
Hi Aaron,

LabGym2 is out and it should fix the error you encountered. But let me know if the error is still there.
