### ISSUE TITLE
LabGym not using my GPU for generating datasets

### ISSUE THREAD

**Issue by LonyTevin** [umyelab/LabGym#7]
Hi,
I was wondering which functional units of LabGym utilise the GPU with TensorFlow. My machine has a Nvidia GTX 1650 Super, but the generate dataset stage only uses my CPU and RAM, and as a result this process takes many hours to process a single video. 

I’m assuming that this is an error, and that all stages of the LabGym pipeline should be utilising my GPU. I was wondering if you might know of a way to troubleshoot this issue – versions of TensorFlow and CUDA are installed on this machine, since DeepLabCut (pose-estimation software (http://www.mackenziemathislab.org/deeplabcut)) is able to use my GPU correctly.

Thanks! :)

**Comment by yujiahu415** [comment]
Hi,

Thanks for raising this issue! First of all, the 'Generate dataset' functional unit is the only one that doesn't utilize the GPU among all 4 functional units. Here are some tips for you to greatly increase the processing speed when generate the dataset:

1. What is the frame size (frame width / frame height) of your video? If it's large, you might want to proportionally downsize it using the option in 'Generate dataset' and 'Analyze behaviors' functional units. One advantage of LabGym over other tools using fixed network structures (like ResNet50, whose desired input shape is large) is that you can customize the input shapes of the networks (the 'Categorizer') and make them small (like, 16 x 16 x 1 for Animation Analyzer and 28 x 28 x 3 for Pattern Recognizer). This drastically increases the processing speed, requires less training samples, and makes the trained network more generalizable. Therefore, large frame size is sometimes unnecessary (overkill) since when doing behavior inference during analysis, the segmented animal blobs will be downsized to the Categorizer's target input shapes.

2. Can you look at your CMD and let me know which step takes so much time? For example, if it's background extraction, you may try to not use the entire duration of the video for it. You can specify a shorter time window (typically 30 ~ 60 seconds) during which the animal is moving around for background extraction.

3. Since the 'Generating dataset' uses CPU and RAM, you may want to set a virtual memory for your Windows: https://www.windowscentral.com/how-change-virtual-memory-size-windows-10. This would make your computer utilize hard drive space when its RAM is used up. Please make sure not to set the virtual memory on your system drive (C drive) and always leave your system drive enough free space, which ensures the smooth processing of your system.

Hope these solve the issue and let me know if they don't or if you have other questions.

**Comment by LonyTevin** [comment]
Hi, 

1: My videos are 928 x 576 pixels in size. Does reducing the input shapes of the networks as you describe have any negative drawbacks? ie: is the classifier less likely to correctly segment the animals? 

2: It doesn’t appear that the background extraction takes too long, but instead the ‘generating data’ step. However, the videos are 3 hours long, so it is reasonable to expect it to take some time. I had tried using a smaller time window, but this generated false segmentation where LabGym detects the floor of the chamber as the background  (see example below), I assume due to low light conditions and camera bitrate creating apparent motion).  I was hoping that allowing LabGym to use the entire duration of the video for background subtraction might alleviate this problem, atleast partially.

![test_0_20_std0](https://user-images.githubusercontent.com/103325790/175819227-0af3c3de-005a-4fe4-89a9-2dbfd3d98bf4.jpg)

3: I shall try setting up some virtual memory to see if that’ll speed it up the process – I never would have thought of that! 

Thank you so much :)

**Comment by yujiahu415** [comment]
Hi,

The video frame size isn't that large but you may still downsize it since the duration of video is long. You may have an estimation of the sizes of segmented animal blob and the input of the Categorizer would be. For example, let's suppose the frame size of your video is 1000 x 1000 and that of segmented animal blob is about 200 x 200 and input of the Categorizer is 32 x 32. The segmented animal blob (200 x 200) will be downsized to 32 x 32 when input into the Categorizer anyway. Therefore, as long as the size of the animal blob is larger than the input size of the Categorizer, there won't be obvious negative drawbacks. 

As for how to determine the input size of the Categorizer, I would say 64 might be a number at large side based on my experience. I used 8 or 16 for larva videos as their body shapes, rather than the detailed body features, is important to the behavior categorization in most scenarios; and used 32 or 64 for mouse / rat videos as some of the detailed features like paws / ears are also important for the behavior categorization.

Using a 3-hour time window for background subtraction would be slow and might not be necessary. Do you mind sending me a sample video of yours via google drive or dropbox to henryhu@umich.edu so that I can take a look and provide specific suggestions?

Thanks!
