### ISSUE TITLE
issue with "train categorizers"

### ISSUE THREAD

**Issue by vzimmern** [umyelab/LabGym#78]
Thanks for a wonderful piece of programming. It has been absolutely transformative in our research project on gene therapy in mice. I was really struggling to get anywhere with DeepLabCut and your piece of programming has helped our project along immensely. 

I have a question about the "training categorizer" step. I am on a Macintosh laptop in a Python virtual environment. LabGym installs correctly and runs smoothly until I get to this step. 

Here is the setup:

<img width="1296" alt="Capture d’écran 2023-11-22 à 3 38 19 PM" src="https://github.com/umyelab/LabGym/assets/139922549/16a677e3-7051-435d-acee-872959d37a37">

And the error in Terminal is:

<img width="1709" alt="Capture d’écran 2023-11-22 à 3 39 01 PM" src="https://github.com/umyelab/LabGym/assets/139922549/408ffaf3-ab74-4a2c-8154-c02ad8c67959">

I am struggling to make sense of the error. I am happy to provide any other information needed in order to get an answer. 

best,
Vincent Zimmern, MS, MD
<img width="1296" alt="Capture d’écran 2023-11-22 à 3 38 19 PM" src="https://github.com/umyelab/LabGym/assets/139922549/d3328e78-cbd0-4860-83a7-c49879d6a979">
<img width="1709" alt="Capture d’écran 2023-11-22 à 3 39 01 PM" src="https://github.com/umyelab/LabGym/assets/139922549/2eeb27e8-5248-4325-b9cb-28514ff5b64a">

**Comment by yujiahu415** [comment]
Hi Vincent,

Thank you for the nice comments!
This issue may be because too few examples in certain behavior category. But I need more information to be sure. So how many pairs of behavior examples in each behavior category (folder)? Can you also double check the behavior examples to see whether they are all in pairs (one animation + one pattern image, with the same name but different file extension)? Thanks!

**Comment by vzimmern** [comment]
There were 2 behavior types that had fewer than 100 pairs -- one only had 1 pair and the other had 21 pairs. What's the minimum number of behaviors that are needed? 

Thanks again not only for such a nice piece of useful code (I'm raving about it to my colleagues) but also for such quick responses on Github.

**Comment by yujiahu415** [comment]
You need to at least have 10 pairs of examples for each category to enable the training. You can either add in more training examples or just delete that category if its frequency is also very low in your videos to analyze. Generally, the more training examples, the higher accuracy of the Categorizer.

**Comment by yujiahu415** [comment]
By the way, I saw that you include body parts in pattern images with the STD of 0. You probably could try higher STD, like 50. Higher STD typically reduce unnecessary details of the body parts and may enhance the learning efficiency. But since you already generated and sorted the examples with STD as 0, you may first try Categorizer with different complexity and input size, if the training accuracy is not satisfying.
